### ISSUE TITLE
Could you please share the binary that you have used

### ISSUE THREAD

**Issue by KA2010** [Olasergiolas/TFG#17]
for example 
bin/upnpd

**Comment by sgIOlas** [comment]
I'd rather not upload proprietary binaries like that here. You can instead get the 1.0.11.128 firmware version from [here](https://www.downloads.netgear.com/files/GDC/R7000/R7000-V1.0.11.128_10.2.112.zip) and extract it using binwalk. The binary can be found at _"squashfs-root/usr/sbin/upnpd"_ 😉 .

**Comment by KA2010** [comment]
what different between what you use and this one you suggest?

**Comment by sgIOlas** [comment]
They are the same! I used that one for my R7000 writeup.

**Comment by KA2010** [comment]
root@cdacc56dce42:~/examples/rootfs_netgearR7000/_R7000-V1.0.11.128_10.2.112.chk.extracted/squashfs-root# ls
bin
I did not get as your path squashfs-root/usr/sbin/upnpd, as you see I got just bin folder and it's empty

**Comment by KA2010** [comment]
What command you use to run the fuzzer?

**Comment by KA2010** [comment]
I got this, thanks
